---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 3284730061-bJAsjlc6bIZD5ABzDoQW6RinL2VFWwsslCdORJQ
:access_token_secret: NGgMHdpFKMvfVXjxbrq9kmsZUR2guDqW2xC7HeCRUOjsr
